# Generated by Django 4.1.11 on 2023-09-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cost", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=50)),
                ("locality", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("link", models.URLField()),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
